### PR TITLE
LPS-148909 | master

### PR DESCRIPTION
**Pull request by ces-sontruong**
Please help me review this PR and give me a feedback. Thank you!
Ticket: [LPS-148909](https://issues.liferay.com/browse/LPS-148909)

### CODE REVIEW

**Comment by ces-totrinh** [comment]
@sontruongces Please help double-check your changes, It still doesn't solve the issue. Thanks.
btw, it seems like this ticket wants to revert the change reported in [LPS-144067](https://issues.liferay.com/browse/LPS-144067). I think it should be better to reconfirm it.

**Comment by ces-sontruong** [comment]
@tototrinh I updated the PR, I asked team about conflict with [LPS-144067](https://issues.liferay.com/browse/LPS-144067) like you said in the comment above. The message they want to change in this ticket is a different place with that ticket. More detail you can see [here](https://issues.liferay.com/browse/LPS-148909#comment-2642121). Thank you!

**Comment by ces-sontruong** [comment]
**Note:** 
I found the definition for this function [here](https://issues.liferay.com/browse/LPS-142259#description-val).

- Use case 1: The warning message is "_Info: Respondents can see all submitted form data. Avoid requesting personal or sensitive information._"

- Use case 2: The warning message is "_Info: Your responses will be visible to all form respondents. Avoid entering personal or sensitive data._"

The _dismissable_ variable used to check the alert message that can be close or not. I see it's value is different between 2 use cases so I used it to check the message.

**Comment by ces-totrinh** [comment]
It looks good to me. Thanks.
Forwarded here: liferay-ts-reviewer#31

**Pull request closed without merging**
