### PR TITLE
LPS-184641 Upgrade process

### PR DESCRIPTION
**Pull request by ces-totrinh**
Hi @locpham97,
Please help review this PR and leave your comments.
# Motivation
In this PR, I solve 1 tasks:
[LPS-184641](https://issues.liferay.com/browse/LPS-184641) [BE] Upgrade processes to update the existing folders
# Proposed Solution
Adding the new column "allowedPropaganda" with "boolean" data type and default data is false.
Note that should add `upgrade.database.auto.run=true` to portal-ext.properties restarting the server for testing.
See the [article](https://help.liferay.com/hc/en-us/articles/360056333511-Auto-Upgrade-in-DXP-7-3-and-Above) for more information.

Thanks!

### CODE REVIEW

**Comment by ces-locpham** [comment]
LGTM, @tototrinh

**Review by ces-locpham — APPROVED** [review]

**Comment by ces-totrinh** [comment]
@locpham97, I update the code based on the field name change. Thanks.

**Comment by ces-locpham** [comment]
LGTM, I tested it , it works good.
Thanks,
Loc

**Review by ces-quanhuynh — APPROVED** [review]

**Comment by ces-totrinh** [comment]
@hhtank, this PR is passed our review. Please have a look. Thanks.

**Comment by hhtank** [comment]
Hi team, this PR looks good to me. Feel free to proceed next steps. Thanks,

**Pull request closed without merging**
