### PR TITLE
LPS-143126 Changes MySitesItemSelectorView display tab name to be "All Sites" for Admin

### PR DESCRIPTION
**Pull request by ces-hongvo**
Reproduce: https://issues.liferay.com/browse/LPS-143126
PTR solution: https://issues.liferay.com/browse/PTR-2751

### CODE REVIEW

**Comment by ces-totrinh** [comment]
I think you could use PermissionThreadLocal.getPermissionChecker() instead of adding themeDisplay as a parameter. And creating a variable `permissionChecker` would be better.

**Comment by ces-hongvo** [comment]
hi @tototrinh 
I updated the PR. Please be noted.
Thank you.

**Comment by ces-totrinh** [comment]
Look good to me. Thanks.

**Comment by ces-totrinh** [comment]
liferay-ts-reviewer#13

**Pull request closed without merging**
