### PR TITLE
[TS] LPP-45423 > LPS-119041 DevTools failed to load SourceMap

### PR DESCRIPTION
**Pull request by chileces**
Dear Ms. ToTo,
Please help me to review this solution for the ticket [LPP-45423](https://issues.liferay.com/browse/LPP-45423)
Solution:
In order to make the waring disappear, we have to escape all sourceMapping markers in js & css while minifying at ComboServlet.

Thank you very much,
Chi

### CODE REVIEW

**Comment by ces-totrinh** [comment]
Please help double check, I still see warnings when not adding
**javascript.fast.load=falseminifier.enabled=false**
Edit: Will see warnings when the bundle is started and not on page reload.
Thanks.

**Comment by chileces** [comment]
thank you @tototrinh ,i could not reproduce your issue. but let me test it in more cases.
@holatuwol if you have some time, could you involve this PR in advance?

**Comment by holatuwol** [comment]
ci:test:bundle

**Comment by holatuwol** [comment]
@chileces I did a quick smoke test, and I saw one warning message when I attempt to create a new basic web content.

```
DevTools failed to load source map: Could not load content for http://localhost:8080/dialog_definition.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Comment by chileces** [comment]
> @chileces I did a quick smoke test, and I saw one warning message when I attempt to create a new basic web content.
> 
> ```
> DevTools failed to load source map: Could not load content for http://localhost:8080/dialog_definition.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
> ```

Thank you for your reviewing @holatuwol , it is complicated for me to fix for dialog_definition.js since this belongs to CKEditorOnEditorCreateDynamicInclude:59 with a different implement than other functions (eg JSBundleConfigTopHeadDynamicInclude:102), it is too risky to refactor to just fix this issue. i will try to fix it

**Comment by chileces** [comment]
@tototrinh please help to verify it again. 
Chi

**Pull request closed without merging**
